In [2]:
import numpy as np
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [2]:
%timeit my_arr2 = my_arr * 2

1.02 ms ± 13.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [3]:
%timeit my_list2 = [x * 2 for x in my_list]

46.1 ms ± 1.61 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## ndarray

In [4]:
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [5]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [6]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [7]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

### dtype and astype

In [4]:
arr1 = np.array([1 , 2 , 3] , dtype=np.int64)
arr2 = np.array([1 , 2 , 3] , dtype=np.int32)
arr1.dtype

dtype('int64')

In [5]:
arr2.dtype

dtype('int32')

In [6]:
arr = np.array([1 , 2 , 3 , 4 , 5])
arr.dtype

dtype('int32')

In [9]:
arr2 = arr.astype(np.float64)
arr2.dtype

dtype('float64')

In [10]:
arr2 = np.ones_like(arr)
arr2

array([1, 1, 1, 1, 1])

In [11]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

### Arithmetic with NumPy Arrays

In [3]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [4]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arr - 3

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [6]:
arr < (arr -2)

array([[False, False, False],
       [False, False, False]])

### Array oriented programming

In [16]:
points = np.arange(0, 5)
points

array([0, 1, 2, 3, 4])

In [17]:
xs, ys = np.meshgrid(points, points)
xs

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [18]:
ys

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [21]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [4.        , 4.12310563, 4.47213595, 5.        , 5.65685425]])